security:
    # https://symfony.com/doc/current/security.html#c-hashing-passwords
    password_hashers:
        App\Entity\User: 'auto'
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        users:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false
        login:
            pattern: ^/api/auth
            stateless: true
            json_login:
                username_path: email
                check_path: /api/auth
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api/
            stateless: true
            provider: users
            jwt: ~

    access_control:
        - { path: ^/api/auth$, roles: PUBLIC_ACCESS } # Allows login
        - { path: ^/api$, roles: PUBLIC_ACCESS } # Allows accessing API documentation
        - { path: ^/api/docs$, roles: PUBLIC_ACCESS } # Allows accessing API documentation
        - { path: ^/api/account$, roles: PUBLIC_ACCESS, methods: ['POST'] } # Allows create user
        - { path: ^/api/profile, roles: PUBLIC_ACCESS } # Public side
        - { path: ^/api/users/me, roles: IS_AUTHENTICATED_FULLY } # Own user account
        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY } # Everything else

when@test:
    security:
        password_hashers:
            App\Entity\User:
                algorithm: md5
                encode_as_base64: false
                iterations: 0
