global:
  checkNewVersion: false
  sendAnonymousUsage: false

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic_conf.yaml

# Maximum debug logging enabled
log:
    level: "DEBUG"

# Access logs enabled for all requests
accessLog: {}

api:
  dashboard: true
  insecure: true # No authentication are required

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  traefik: # this one exists by default
    address: ":8080"
