controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

activitypub_controllers:
    resource:
        path: ../src/ActivityPub/Controller/
        namespace: App\ActivityPub\Controller
    type: attribute

auth:
    path: /auth
    methods: ['POST']
